ERROR(BS_Error_NoError,             "No error")
ERROR(BS_Error_InvalidCharacter,    "Invalid character")
ERROR(BS_Error_UnexpectedEOL,       "Unexpected End of Line")
ERROR(BS_Error_UnexpectedEOF,       "Unexpected End of File")
ERROR(BS_Error_UnexpectedEOE,       "Unexpected End of Expression")
ERROR(BS_Error_UnexpectedSemicolon, "Unexpected Semicolon")
ERROR(BS_Error_InvalidBracketStack, "Invalid bracket stack")
ERROR(BS_Error_NotFound,            "Undefined variable")
ERROR(BS_Error_VariableExists,      "Variable exists")
ERROR(BS_Error_VariableNotSameType, "Variables are not of same type")