TYPE IDENT RUN(bseval_create_variable)
TYPE IDENT EQUALS EXPR RUN(bseval_create_and_assign_variable)
IDENT EQUALS EXPR RUN(bseval_assign_variable)
IDENT SWAP IDENT RUN(bseval_swap_variables)
IDENT BRACKETS EXPR RUN(bseval_array_indexer)
IDENT ARRLEN RUN(bseval_array_length)
PAREN ARGLIST CODEBLOCK RUN(bseval_function)
PAREN ARGLIST RETURNS TYPE CODEBLOCK RUN(bseval_function_returns)
PAREN EXPR RUN(bseval_expr)
IF EXPR CODEBLOCK RUN(bseval_if)
ELSE CODEBLOCK RUN(bseval_else)
WHILE EXPR CODEBLOCK RUN(bseval_while)
FOR IDENT IN BRACKETOPEN EXPR SEPARATOR EXPR BRACKETCLOSE RUN(bseval_for_inin)
FOR IDENT IN PARENOPEN EXPR SEPARATOR EXPR BRACKETCLOSE RUN(bseval_for_exin)
FOR IDENT IN BRACKETOPEN EXPR SEPARATOR EXPR PARENCLOSE RUN(bseval_for_inex)
FOR IDENT IN PARENOPEN EXPR SEPARATOR EXPR PARENCLOSE RUN(bseval_for_exex)
CONTINUE RUN(bseval_continue)
BREAK RUN(bseval_break)
BREAK EXPR RUN(bseval_break_multilevel)
STRUCT IDENT BRACES EXPR RUN(bseval_struct)
NUMBER COLON TYPE IDENT RUN(bseval_struct_entry)
CODEBLOCK RUN(bseval_codeblock)
NUMBER RUN(bseval_number)
STRLIT RUN(bseval_string_literal)
MODIFIER EXPR RUN(bseval_modifier)
EXPR OPERATOR EXPR RUN(bseval_operation)
VARARGS RUN(bseval_vararg_get)
VARARGS BRACKETS EXPR RUN(bseval_vararg_get_at)
RETURN RUN(bseval_return_void)
RETURN EXPR RUN(bseval_return_expr)