TYPE IDENT RUN(bseval_create_variable)
TYPE IDENT EQUALS EXPR RUN(bseval_create_and_assign_variable)
LEND TYPE IDENT RUN(bseval_create_lendable_variable)
LEND TYPE IDENT EQUALS EXPR RUN(bseval_create_and_assign_lendable_variable)
BORROW IDENT FROM IDENT RUN(bseval_borrow_from)
IDENT EQUALS EXPR RUN(bseval_assign_variable)
IDENT SWAP IDENT RUN(bseval_swap_variables)
IDENT BRACKETOPEN EXPR BRACKETCLOSE RUN(bseval_array_indexer)
IDENT CALLED RUN(bseval_called)
IDENT PARENOPEN EXPRLIST RUN(bseval_func_call)
PARENOPEN ARGLIST CODEBLOCK RUN(bseval_function)
PARENOPEN ARGLIST RETURNS TYPE CODEBLOCK RUN(bseval_function_returns)
PARENOPEN EXPR PARENCLOSE RUN(bseval_expr)
IF EXPR CODEBLOCK RUN(bseval_if)
ELIF EXPR CODEBLOCK RUN(bseval_elif)
ELSE CODEBLOCK RUN(bseval_else)
WHILE EXPR CODEBLOCK RUN(bseval_while)
FOR IDENT IN EXPR RANGE EXPR CODEBLOCK RUN(bseval_for)
CONTINUE RUN(bseval_continue)
BREAK RUN(bseval_break)
BREAK EXPR RUN(bseval_break_multilevel)
STRUCT IDENT BRACEOPEN EXPR BRACECLOSE RUN(bseval_struct)
NUMBER COLON TYPE IDENT RUN(bseval_struct_entry)
CODEBLOCK RUN(bseval_codeblock)
NUMBER RUN(bseval_number)
STRLIT RUN(bseval_string_literal)
IDENT RUN(bseval_identifier)
MODIFIER EXPR RUN(bseval_modifier)
VARARGS RUN(bseval_vararg_get)
VARARGS BRACKETOPEN EXPR BRACKETCLOSE RUN(bseval_vararg_get_at)
RETURN RUN(bseval_return_void)
RETURN EXPR RUN(bseval_return_expr)
EXPR OPERATOR EXPR RUN(bseval_operation)